########################################################################################################################
# アプリケーション設定
########################################################################################################################

#-----------------------------------------------------------------------------------------------------------------------
# Spring Framework: メイン
#   * showBanner: バナーは表示しない。
#   * logStartupInfo: スタートアップ情報をロギングしない。
#-----------------------------------------------------------------------------------------------------------------------
spring.main:
  showBanner: false
  logStartupInfo: false
